### ISSUE TITLE
Feedback HW5

### ISSUE THREAD

**Issue by setwith** [xiosky90/blog-RoR-api#1]
Все працює, по роботі коду нарікань немає. Всі реквести API обробляє коректно.

- [x] Можна вдосконалити ініціалізацію проекту добавивши в файл _seed.rb_  
```ruby
Article.create([
                 {
                   title: 'First article',
                   body: 'Some text for article'
                 },
                 {
                   title: 'Second one',
                   body: 'Some more text for article'
                 }
                 ])
```
Таким чином при створенні бази даних відразу будуть створюватись об'єкти в ній.

**Comment by xiosky90** [comment]
Дякую, додав в проект.

**Comment by Kashoid23** [comment]
Гарна ідея з рендером конкретних атрибутів
https://github.com/xiosky90/blog-RoR-api/blob/main/app/controllers/api/v1/articles_controller.rb#L8
ми ще до цього не дійшли, але оскільки вас це вже зацікавило
- [ ] прочитайте https://blog.kiprosh.com/serialization_in_ruby_on_rails_part_three

Найчастіше використовується цей гем https://github.com/rails-api/active_model_serializers
Приклади
https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/getting_started.md
https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/rendering.md

- [ ] Оскільки в самому контроллері згенерованому через скаффолд не видно, щоб було значних змін треба обов'язково прочитати https://guides.rubyonrails.org/action_controller_overview.html щоб мати якесь теоретичне розуміння, як це працює.

**Comment by xiosky90** [comment]
Дякую, прочитаю

**Comment by Kashoid23** [comment]
Думаю, можна закрити ішю! Гарна робота! )
