### ISSUE TITLE
Feedback for HW6

### ISSUE THREAD

**Issue by MaksHostroushko** [xiosky90/blog-RoR-api#3]
Looks awesome!
Just let's add some improvements

1.`Коментар належить автору, якого ми вибрали і статті, в якій ми його створили `
Sorry, but I didn't find validation for this point
Please, add validation or let me know if you already have it

2. https://github.com/xiosky90/blog-RoR-api/blob/main/app/models/comment.rb#L9
Let's avoid duplication. We don't need to duplicate enums every time. We just can call it
`validates :status, inclusion: { in: Comment.statuses, message: 'Status %{value} is not a valid' }`

3. https://github.com/xiosky90/blog-RoR-api/blob/main/app/models/comment.rb#L10..L11
Let's write it in a single row. In this case we will avoid duplication
`validates :author_id, : article_id,  numericality: { only_integer: true }`

4. https://github.com/xiosky90/blog-RoR-api/blob/main/app/controllers/api/v1/comments_controller.rb#L56
It's not the best practice to use hardcoded values. You already have statuses. Just use them
`new_status = @comment.unpublished? ? Comment.statuses[:published] : Comment.statuses[:unpublished]`

**Comment by xiosky90** [comment]
Hello, thanks for notice.
1. Add `validates_associated :articles, :comments` in author model.
2. Rework to your solution.
3. Fix it.
4. Fix it.

Thanks
